content_style: 'img {max-width: 100%;} a {word-break: break-all}'
toolbar: undo redo | fontselect | fontsizeselect | forecolor backcolor | bold italic underline | alignleft aligncenter alignright | outdent indent numlist bullist | link code uploadimage | table |
plugins:
  - link
  - uploadimage
  - textcolor
  - code
  - table
  - lists